spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nurlan@div.edu.az
    password: ehxuayhpoyxebedj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

